### ISSUE TITLE
Electron app fails to launch on Ubuntu 24.04 and derivatives due to new sandbox restrictions

### ISSUE THREAD

**Issue by thre-z** [foundryvtt/foundryvtt#11632]
### What happened?

When attempting to run the Foundry desktop Electron client (any version) on Ubuntu 24.04 and derivatives, Electron crashes with the following error: 
`[15107:0828/094550.686983:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/<user>/foundryvtt/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)`

This is due to a change made by Ubuntu in the [24.04 release](https://discourse.ubuntu.com/t/ubuntu-24-04-lts-noble-numbat-release-notes/39890#unprivileged-user-namespace-restrictions) under Security Improvements -> Unprivileged user namespace restrictions. Looks like Ubuntu is committed to this change and it will be present going forward, and affects any derivatives of Ubuntu that don't specifically revert the change. I have seen this reported on Kubuntu 24.04 as well. 

Some configurations don't appear to be affected yet (perhaps only affecting new installations), but given this will be ongoing I think it should be on Foundry's radar. 

The issue boils down to Electron requesting a sandbox environment which Ubuntu now restricts to users with root permissions only, or those that are explicitly allowed as an exception. I'm unsure if Electron will be able to make these changes as a general fix, and it may be up to each individual Electron app to deal with on their own. Details on Electron's side, including temporary workarounds can be found in their [issue thread](https://github.com/electron/electron/issues/42510).

The quickest and easiest way to work around this for end-users is to launch Foundry with `--no-sandbox` as this disables the sandboxing in Electron. I'm not sure if this is a valid long-term approach as it does disable a major security feature in Electron. 

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Attempt to launch the Foundry desktop client on freshly installed Ubuntu 24.04 desktop. 

### What core version are you reporting this for?

All to date

### Relevant log output

```shell
[15107:0828/094550.686983:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/<user>/foundryvtt/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Thanks for the heads up on this, an unfortunate emerging issue that we'll have to think about how to address.

**Comment by notQuiteTrash** [comment]
Hopefully this isn't a bother, just wanted to voice that I am also having the issue so - can confirm seeing it in Kubuntu 24.04

**Comment by ZirkMcT** [comment]
Another solution is revert the security change, although I am not certain whether this or `--no-sandbox` is the better method.

to deactivate:
`sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0`

to reactivate:
`sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=1`

**Comment by aaclayton** [comment]
Looks like this will be fixed upstream in `electron-builder` version `26.x`:

- https://github.com/electron-userland/electron-builder/issues/8635
- https://github.com/electron-userland/electron-builder/pull/8636

So our current policy on this issue is workaround for now and wait for a permanent fix.

**Comment by aaclayton** [comment]
We have adopted `electron-builder` version `26.x` for our next V13 release. We will test and confirm whether the Ubuntu sandbox restrictions are effectively resolved with this release.

**Comment by Fyorl** [comment]
Internal testing indicates this has been fixed upstream.

**Comment by anathemamask** [comment]
As the tester who initially confirmed process as running fine- Re-opening this issue to admit my folly. It looks like this is still an issue when executing `./foundryvtt` via terminal. This however is an upstream issue with ubuntu 24.04 apparmor and needs to be addressed by either the Electron team or Canonical and has no simple solution for devs to pre-pack as a workaround. 

The guidance for now is for users who wish to execute via terminal instead of double-clicking to exec, to execute the following commands via terminal from the unzipped Foundry VTT folder:
```
sudo chown root:root chrome-sandbox
sudo chmod 4755 chrome-sandbox
```

**Comment by anathemamask** [comment]
https://github.com/electron/electron/issues/41066 appears to be the relevant open electron issue

**Comment by Nao-30** [comment]
@anathemamask @Fyorl @aaclayton 
I guess still beside electron there must be a configured profile generated and provided by the user based on the main cause!

electron depends on chromium similar to app images for sandboxing~ to give a bit more details let's understand the following:

Ubuntu 23.XX and higher versions  implemented a stricter security model through AppArmor that specifically targets unprivileged user namespaces[2](https://blog.mohammed-al-kebsi.space/post/understanding-ubuntu-24-04-appimage-sandbox-restrictions/).

you can review the full article

For a complete understanding of this issue, including technical details, implementation specifics, you can take a look at:

[Technical Deep Dive](https://blog.mohammed-al-kebsi.space/post/understanding-ubuntu-24-04-appimage-sandbox-restrictions/)

For a more direct practical solutions and safest options, you can take a look at:

[Practical Workarounds](https://blog.mohammed-al-kebsi.space/post/fix-appimage-sandbox-issues-ubuntu-24-04/)

---

Basically yhe issue happens because AppImages are FUSE-mounted with `nosuid`, this prevents any set-UID helper from running~

Ubuntu’s default AppArmor policy also disallows unprivileged user namespaces

so now as mentioned the AppImage can use neither the kernel userns nor the setuid sandbox. In short, on Ubuntu 23.++ an electron AppImage is trapped: it's `chrome-sandbox` can’t be made set-UID on the FUSE mount, and userns is blocked (unless you add a custom AppArmor profile to allow it as mentioned in the blog based on [askubuntu.com](https://askubuntu.com/questions/1512287/obsidian-appimage-the-suid-sandbox-helper-binary-was-found-but-is-not-configu#:~:text=flags%3D%28default_allow%29%20)).

By contrast, the `.tar.gz` release is simply unpacked onto a normal filesystem (e.g. `/opt/void`). This means its `chrome-sandbox` binary is on an ordinary ext4 (or similar) partition, not under a FUSE `nosuid` mount. A packager or user **can** then run:

```bash
sudo chown root:root /opt/void/chrome-sandbox 
sudo chmod 4755 /opt/void/chrome-sandbox

```

– granting it the correct owner and set-UID bit. Once the helper is root-owned, and correct permissions are set the Chromium sandbox should run as intended. Because the tar.gz's files aren’t subject to AppImage/AppArmor quirks and stuff, the sandbox must work normally after this fix 

and ofc (No special AppArmor profile is needed for the tar install, unlike the AppImage case)
