### ISSUE TITLE
It is not possible to register custom Dice.termTypes to extend the functionality of existing types like MathTerm. Additional problems with simplification and flavor combination.

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#7392]
Add RollTerm.canHaveFlavor boolean or similar, and test against that in Roll._splitParentheses instead of having special case for each roll term that do support it. This allows easily adding custom roll terms that support and/or want flavor.

### User Experience

End users zero difference.

Module and system devs can avoid monkeypatching Roll._splitParentheses

### Priority/Importance

Low. Reduces need for monkeypatching and makes roll terms more flexible.

**Comment by mkahvi** [comment]
Forgot to come back to this. This ended up not working

After removing all overrides to handle flavors system side, I still get these for flavoring custom terms.
```
foundry.js:59187 Error: Unresolved StringTerm undefined[awesome flavor] requested for evaluation
    at StringTerm.evaluate (foundry.js:11730:11)
    at RollPF._evaluate (foundry.js:9292:42)
    at RollPF.evaluate (foundry.js:9256:25)
```
```
foundry.js:11730 Uncaught (in promise) Error: Unresolved StringTerm undefined[awesome flavor] requested for evaluation
[No packages detected]
    at StringTerm.evaluate (foundry.js:11730:11)
    at RollPF._evaluate (foundry.js:9292:42)
    at RollPF.evaluate (foundry.js:9256:25)
```
Using the custom term without flavor works without issue.

**Comment by mkahvi** [comment]
After altering the code some more, I get this error instead:
```
foundry.js:59187 TypeError: Cannot read properties of undefined (reading 'total')
    at get total [as total] (sizerollterm.mjs:41:22)
    at foundry.js:9462:34
    at Array.reduce (<anonymous>)
    at RollPF.simplifyTerms (foundry.js:9448:28)
```
It's attempting to throw away the term and force it into a number instead of adding the flavor to the term so it can handle it itself.

The bit of code that error is coming from is commented with "Combine StringTerm with a prior non-operator term"

**Comment by mkahvi** [comment]
This may also be an issue with adding the roll term handling in wrong place? I've been staring at this for a while, and I can't actually find a location where Foundry automatically accounts for new terms, so it seems to be whatever people think of.  But I think I've come to the conclusion I was supposed to override `_classifyStringTerm` instead of whatever I am doing instead despite the underscore.

Custom roll terms definitely need documentation on how to make them since this has been a lot of guesswork that seems to have gone completely in the wrong direction.

**Comment by aaclayton** [comment]
@mkahvi I'd like to try and help, but I'm afraid this issue - like our Roll API I suppose - is hard to understand. Could you take a big step back and outline the problem you are trying to solve and the difficulty you encountered? I think we can turn this into a core improvement to make this easier, but I need to understand your use case more clearly in order to figure out how to proceed.

**Comment by mkahvi** [comment]
I've implemented a new roll term that is essentially a function similar to the Math functions, but returns dice instead of a number.

The function signature is simplified as `sizeRoll(x, y)` and produces `XdY` dice formula, with all the parameters being able to hold formulas like math functions so you can do `sizeRoll(floor(@classes.X.level / 3), 6)[Base] + 5[Bonus]` or similar.

I was also planning on adding other functions, but they are simpler than the above example.

Currently this seems to be easiest to do by replacing `_splitParentheses` and implementing recognition of the term there like Math functions are done by Foundry, or at least that is the easiest point of entry without having to re-invent the wheel so to speak. This approach however necessitates overriding also simplifyTerms() to avoid the logic there from crashing since it assumes the terms are evaluated already `.total`.

I _suppose_ I could override `Roll.parse()` and add my term recognition there and use the following ParentheticalTerm to build them instead? I didn't think of testing that. Or at least I don't recall testing that.

**Comment by mkahvi** [comment]
Using Roll.parse() override is showing some promise, though it's still a lot of custom code.

There's some issues with special parameters for another roll term: `sizeReach("M", false, "tall")`  where the first parameter can be a special string or a formula that resolves into a number.

**Comment by aaclayton** [comment]
@mkahvi I'm afraid your example is still not entirely clear. Am I correct to assume that you are doing something like:
```js
class SizeTerm extends DiceTerm {
  static REGEXP = "" // your matching pattern here
}
```
Then you are registering this term as:
```js
CONFIG.Dice.termTypes.SizeTerm= SizeTerm;
```
This would be the basic structure for defining and extending a custom term type. Using this minimal example, could you explain to me where things start to go wrong for you?

**Comment by mkahvi** [comment]
`class SizeRollTerm extends RollTerm` rather than `DiceTerm`

Didn't define `static REGEXP`, since `MathTerm` doesn't use it either. And if I'm defining the contents of the parenthesis part with it, I've lost all benefit of using what Foundry has already.

Don't know how to explain it better, so I'll just link the sources.

The currently functioning implementation is this:  
<https://gitlab.com/foundryvtt_pathfinder1e/foundryvtt-pathfinder1/-/blob/ff55048c53b8600a554a24f5cba10237166ebcd2/module/dice/terms/sizerollterm.mjs>

`simplifyTerms()` override to not break the term with `.total` when Foundry adds flavor to it:  
<https://gitlab.com/foundryvtt_pathfinder1e/foundryvtt-pathfinder1/-/blob/ff55048c53b8600a554a24f5cba10237166ebcd2/module/dice/roll.mjs#L67-73>

`_splitParentheses()` override:  
<https://gitlab.com/foundryvtt_pathfinder1e/foundryvtt-pathfinder1/-/blob/ff55048c53b8600a554a24f5cba10237166ebcd2/module/dice/roll.mjs#L124-149>

**Comment by aaclayton** [comment]
Just linking me to your code does not accomplish the task of helping to simplify the problem to the minimum complexity needed to understand the problem.

**Comment by mkahvi** [comment]
I suppose.

Another attempt then. Kinda re-iterating things at this point:

`RollTerm`s that are NOT derivative of `DiceTerm` are not recognized.

- Requires manual recognition somewhere. 
  - `CONFIG.Dice.termTypes` is __only__ used by `RollTerm.fromData()`, which does nothing for Roll.create()
- This gets more complicated if you want function-like terms.
  - Currently you either add them to `Math`, override `_splitParenthesis()`, or combine `StringTerm`+`ParentheticalTerm` in `Roll.parse()` override after calling super.
  - This could be somewhat solved by common function term that math term also inherits and use that as basis, though unlike MathTerm, it doesn't need to record the function name.
  - This would allow the function name in _splitParenthesis() to be used to recognize the function term at the same time of recognizing math functions.

`RollTerm`s that do NOT remain wholly `StringTerm`s for `simplifyTerms()` and do not produce numbers without evaluation, _break_ in simplifyTerms() currently.

- Preferably these terms would combine flavor into themselves and exit before simplifyTerms() attempts to get .total out of them without evaluation.
- This is what the original topic of this issue was about, ability for RollTerm to signal that the flavor can be merged into them _without_ attempting to convert the term itself into something else.
  
The above would be solved by adding something like the following pseudocode near the top of simplifyTerms()
```js
if (currentTerm.isFlavor && prior.canHaveFlavor ) {
  prior.options.flavor = currentTerm.flavorText;
  return terms;
}
```

I really don't know how to explain the problems and what is needed any better, so if this isn't enough, I'm out of ideas.

**Comment by aaclayton** [comment]
Thanks for the summary, this helps me understand better. My understanding of the key problems are:

1. It's not possible to add a custom `Dice.termTypes` because this is only used for lookup and not for parsing. (this may be intended)
2. It's not possible to replace an existing entry in `Dice.termTypes` because the classes used are hard-coded as part of the Roll class parsing methods.
3. `simplifyTerms` assumes that any remaining term at the end of parsing is a string, if this is not the case things break
4. The original issue with merging flavor text that would allow flavor attached to adjacent terms to be merged into a `RollTerm`

I think for problems 1 and 2, the answer is likely that you cannot register custom term types but rather the software has some key assumptions about what the possible term types are. However, it should be possible to replace a term type to add some extra functionality to it, for example replacing `MathTerm` with `MyCustomMathTerm`.

For problems 3 and 4, I don't have a clear answer right now.  I will have to think about this.

**Comment by mkahvi** [comment]
I think this is largely no longer relevant with the function term addition and removal of support for custom terms. I'm gonna close this as such.
