### ISSUE TITLE
Toggling visibility of text drawings does not update for the GM until refresh

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9796]
Originally reported by andysaysgrr https://discord.com/channels/170995199584108546/1065764070680186930/1130786051284287588

**ALL MODULES DISABLED?** TRUE
**OS, Hosting, Browser (if applicable)**:  Both standalone application and Chrome browser

**Short Description of bug**: Toggling the visibility of text or tiles does not update the scene for the gamemaster's view. Toggling text appears to work for players but not GM, but toggling the visibility of a tile doesn't appear to work for either GM or player views. Works fine for tokens. Reloading the scene updates the view.

**Simple steps to reproduce the bug**: Create scene with a background map. Add a text item. Add a tile item. Try toggling their visibility.

**Screenshots and/or console errors**:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/a54f18c4-a4b8-40d7-8cef-8053874c1a2f)

**Comment by Fyorl** [comment]
I wasn't able to reproduce the issue with tile toggling. That appeared to work fine (it may have been fixed on our dev branch). When toggling text drawings I did notice that the drawing border was rendered transparent, but the text wasn't.

**Comment by andy-jones** [comment]
It appears the issue with the tile visibility was user error on my part, sorry. However the text drawings are still not rendering transparent when toggled, following the update to Version 11 Stable - Build 306 this morning.
